from .CGNet import *
from .BiSeNet_resnet import *
from .BiSeNet_xception import *
from .DeepLabV3plus_resnet import *
from .DeepLabV3plus_xception import *
from .DenseASPP import *
from .DFN import *
from .ENet import *
from .ESPNet import *
from .PSPNet import *
from .SegNet import *
from .resnet import *
from .xception import *
